// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/WH-5/push-service/internal/biz"
	"github.com/WH-5/push-service/internal/conf"
	"github.com/WH-5/push-service/internal/data"
	"github.com/WH-5/push-service/internal/server"
	"github.com/WH-5/push-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bizfig *conf.Bizfig, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	pushRepo := data.NewPushRepo(dataData, logger)
	pushUsecase := biz.NewPushUsecase(bizfig, pushRepo, logger)
	pushService := service.NewPushService(confServer, pushUsecase)
	grpcServer := server.NewGRPCServer(confServer, pushService, logger)
	httpServer := server.NewHTTPServer(confServer, pushService, logger)
	app := newApp(logger, grpcServer, httpServer, confServer)
	return app, func() {
		cleanup()
	}, nil
}
