server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
  name: "push-service"
  version: "1.0"
  registry: #这个在容器里的时候要加上
    consul: localhost:8500
data:
  database:
    driver: postgres
    #    source: postgres://root:whwhwhwhwhwhwhwh12321wh@database:5432/friend_service?sslmode=disable&TimeZone=Asia/Shanghai
    source: postgres://root:whwhwhwhwhwhwhwh12321wh@localhost:5432/friend_service?sslmode=disable&TimeZone=Asia/Shanghai
  redis:
    #    addr: redis:6379
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    password: "123456"
    dial_timeout: 5s
bizfig:
  JWT_SECRET_KEY: test #jwt的密钥